import { OnModuleInit } from '@nestjs/common';
import { AuthService } from '../auth/auth.service';
import { JobsService } from '../jobs/jobs.service';
import { PlexAnalyticsService } from '../plex/plex-analytics.service';
import { PlexServerService } from '../plex/plex-server.service';
import { PlexUsersService } from '../plex/plex-users.service';
import { SettingsService } from '../settings/settings.service';
import { WebhooksService } from './webhooks.service';
export declare class PlexPollingService implements OnModuleInit {
    private readonly authService;
    private readonly settingsService;
    private readonly jobsService;
    private readonly plexServer;
    private readonly plexUsers;
    private readonly webhooksService;
    private readonly plexAnalytics;
    private readonly logger;
    private readonly enabled;
    private readonly intervalMs;
    private readonly watchedScrobbleThreshold;
    private readonly immaculateScrobbleThreshold;
    private readonly forceBothScrobbleThreshold;
    private readonly minDurationMs;
    private readonly nowPlayingLogIntervalMs;
    private readonly nowPlayingLogProgressStepMs;
    private readonly recentlyAddedIntervalMs;
    private readonly libraryNewDebounceMs;
    private readonly lastBySessionKey;
    private static readonly SESSION_AUTOMATION_STATE_TTL_MS;
    private static readonly MAX_COLLECTION_JOB_ATTEMPTS;
    private readonly sessionAutomationStateById;
    private readonly nowPlayingLogStateBySessionKey;
    private static readonly COLLECTION_COOLDOWN_MS;
    private readonly collectionCooldownUntilByPlexUser;
    private readonly pendingCollectionRunsByPlexUser;
    private lastRecentlyAddedPollAtMs;
    private lastSeenAddedAtSec;
    private lastLibraryNewTriggeredAtMs;
    private pendingLibraryNew;
    constructor(authService: AuthService, settingsService: SettingsService, jobsService: JobsService, plexServer: PlexServerService, plexUsers: PlexUsersService, webhooksService: WebhooksService, plexAnalytics: PlexAnalyticsService);
    onModuleInit(): void;
    poll(): Promise<void>;
    private lastPolledAtMs;
    private setCollectionCooldown;
    private buildSessionAutomationId;
    private getOrCreateSessionAutomationState;
    private getSessionJobStatus;
    private setSessionJobStatus;
    private canScheduleSessionJob;
    private pruneSessionAutomationState;
    private enqueueCollectionRun;
    private dequeueNextPendingCollectionRun;
    private runCollectionJobNow;
    private flushPendingCollectionRuns;
    private pollOnce;
    private pollRecentlyAdded;
    private toSnapshot;
    private mergeSnapshot;
    private formatNowPlayingTitle;
    private formatNowPlayingProgress;
    private shouldLogNowPlaying;
    private updateNowPlayingLogState;
    private logNowPlayingStarted;
    private logNowPlayingProgress;
    private logNowPlayingEnded;
    private getProgressRatio;
    private maybeTriggerWatchedAutomation;
    private handleEndedSession;
}
