name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Immaculaterr.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: It’s hard to…
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      placeholder: I’d like the app to…
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you’ve considered (optional)
    validations:
      required: false

